name: Visual Regression Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./vm
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - run: sudo apt install fonts-ipafont fonts-ipaexfont
      - run: npm ci
      - name: workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull
      - run: npm run build-storybook-2
      - run: npm run static-screenshot
      - run: npx reg-suit run
        env:
          REGSUIT_GITHUB_CLIENT_ID: ${{ secrets.REGSUIT_GITHUB_CLIENT_ID }}
          REGSUIT_BUCKET_NAME: ${{ secrets.REGSUIT_BUCKET_NAME }}
